---
user: deploy
group: deploy
tag: roamtheblog
rackup: config.ru
pid: tmp/thin.pid
log: log/thin.log
port: 3000
timeout: 30
max_conns: 1024
max_persistent_conns: 512
environment: production
chdir: /var/www/roamtheblog
servers: 2
daemonize: true
address: 0.0.0.0
require: []